// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsCatalogService.API.Model.Data;

#nullable disable

namespace ProductsCatalogService.API.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20240822065738_dataseed")]
    partial class dataseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductsCatalogService.API.Model.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "SoundPro",
                            Country = "USA",
                            IsAvailable = true,
                            Price = 150,
                            ProductCategory = "Electronics",
                            ProductDescription = "Noise-cancelling over-ear headphones with Bluetooth connectivity.",
                            ProductName = "Wireless Headphones"
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "TechCorp",
                            Country = "China",
                            IsAvailable = true,
                            Price = 799,
                            ProductCategory = "Electronics",
                            ProductDescription = "Latest model with 128GB storage, 5G, and a high-resolution camera.",
                            ProductName = "Smartphone"
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "RunFast",
                            Country = "Germany",
                            IsAvailable = true,
                            Price = 120,
                            ProductCategory = "Footwear",
                            ProductDescription = "Lightweight running shoes with breathable mesh upper.",
                            ProductName = "Running Shoes"
                        },
                        new
                        {
                            ProductId = 4,
                            Brand = "KitchenMaster",
                            Country = "UK",
                            IsAvailable = true,
                            Price = 40,
                            ProductCategory = "Home Appliances",
                            ProductDescription = "1.5-liter electric kettle with auto shut-off and boil-dry protection.",
                            ProductName = "Electric Kettle"
                        },
                        new
                        {
                            ProductId = 5,
                            Brand = "TimePiece",
                            Country = "Switzerland",
                            IsAvailable = true,
                            Price = 250,
                            ProductCategory = "Accessories",
                            ProductDescription = "Stainless steel analog wristwatch with water resistance.",
                            ProductName = "Wrist Watch"
                        },
                        new
                        {
                            ProductId = 6,
                            Brand = "GameOn",
                            Country = "USA",
                            IsAvailable = false,
                            Price = 1200,
                            ProductCategory = "Electronics",
                            ProductDescription = "High-performance laptop with 16GB RAM, 512GB SSD, and GTX 1660 Ti.",
                            ProductName = "Gaming Laptop"
                        },
                        new
                        {
                            ProductId = 7,
                            Brand = "SmoothieMaster",
                            Country = "Canada",
                            IsAvailable = true,
                            Price = 70,
                            ProductCategory = "Home Appliances",
                            ProductDescription = "500-watt blender with multiple speed settings and a pulse feature.",
                            ProductName = "Blender"
                        },
                        new
                        {
                            ProductId = 8,
                            Brand = "FashionWear",
                            Country = "Italy",
                            IsAvailable = true,
                            Price = 300,
                            ProductCategory = "Clothing",
                            ProductDescription = "Genuine leather biker jacket with zipper closure and side pockets.",
                            ProductName = "Leather Jacket"
                        },
                        new
                        {
                            ProductId = 9,
                            Brand = "TabTech",
                            Country = "South Korea",
                            IsAvailable = true,
                            Price = 250,
                            ProductCategory = "Electronics",
                            ProductDescription = "10-inch tablet with 64GB storage and HD display.",
                            ProductName = "Tablet"
                        },
                        new
                        {
                            ProductId = 10,
                            Brand = "PhotoSnap",
                            Country = "Japan",
                            IsAvailable = false,
                            Price = 500,
                            ProductCategory = "Electronics",
                            ProductDescription = "24MP DSLR camera with a versatile lens kit.",
                            ProductName = "Digital Camera"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
